### ISSUE TITLE
update the reasons for each case

### ISSUE THREAD

**Issue by eubinecto** [eubinecto/politetune#38]
## What?
Update the reasons with this:
```yaml
friends and junior:
  Comfortable and informal:
    politeness: 1
    reason: A comfortable and informal situation is a very relaxed situation for all, so friends and juniors will use the intimate style (banmal). 
  formal:
    politeness: 2
    reason: If there are observers around or the situation is more formal, then the speaker is not completely relaxed. Therefore, it is most appropriate to use the formal (-yo) form. 
boss at work:
  Comfortable and informal:
    politeness: 2
    reason: In a less formal situation, for example a company dinner, employees feel a little more relaxed around their bosses, and thus they may use the formal (-yo) form. 
  formal:
    politeness: 3
    reason: In a highly formal environment, e.g. an important meeting, employees will always use the honorific (-bnida) form. This shows the appropriate respect in a high-profile context. 
adult family:
  Comfortable and informal:
    politeness: 1
    reason: With in a relaxed setting, using the intimate style (banmal) is standard, even if a family member is older than you. 
  formal:
    politeness: 2
    reason: If someone outside of the family, e.g. a neighbour, is part of the conversation too, then it is common to use the formal (-yo)¬ form towards family members to seem polite in front of others. 
```

**Comment by eubinecto** [comment]
##  Refining the sentences
I've revised the rules to make it sound more natural and clear:
```yaml

# https://docs.google.com/document/d/13ZiGYDxqpWb93JALVOLSNLo0lHO73TYjKmEKOlCpc4w/edit
friends and junior:
  comfortable & informal:
    politeness: 1
    reason: A comfortable and informal situation is a very relaxed situation for all, so you may speak to your friends and juniors without honorifics (`-어`).
  formal:
    politeness: 2
    reason: If there are observers around or the situation is rather formal, then you and your listener may not find it completely relaxing. If so, you should speak with polite honorifics (`-어요`) even when you are speaking to your friends and juniors.
boss at work:
  comfortable & informal:
    politeness: 2
    reason: If you are in an informal situation with your boss, e.g. a company dinner, then you and your boss may find it a little more relaxing than at the work place. Therefore, it is not necessary to speak with formal honorifics, and you may speak to your boss with polite honorifics (`-어요`).
  formal:
    politeness: 3
    reason: If you are in a highly formal environment, e.g. an important meeting, you should always speak with formal honorifics (`-습니다`). This shows the appropriate respect to your listeners in a high-profile context.
adult family:
  comfortable & informal:
    politeness: 1
    reason: If you are in a relaxed setting, it is customary and allowed to speak to your family members without honorifics (`-어`) even when they are older than you.
  formal:
    politeness: 2
    reason: If someone outside of your family, e.g. a neighbour, is partaking the conversation too, then it is customary to speak to your family with polite honorifics (`-어요`) so that you and your family come acorss polite to the outsiders.

```
